### Sign-up

POST http://localhost:8080/public/v1/auth/sign-up
Content-Type: application/json

{
  "name": "German",
  "surname": "Bogatov",
  "email": "bogat1weee@mail.ru",
  "password": "23Bogatov"
}

### Sign-in

POST http://localhost:8080/public/v1/auth/sign-in
Content-Type: application/json

{
  "email": "bogat1weee@mail.ru",
  "password": "qwerty12345"
}

### Refresh
GET http://localhost:8080/public/v1/auth/refresh/f9177080-c5f2-487f-b095-ac1aaa1127bf
Content-Type: application/json


### Get User By ID
GET http://localhost:8080/public/v1/users/713197b2-1d4d-4482-8dd3-3fff12e58a32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidXNlcnMiXSwiZXhwIjoxNzI3NTc0OTI1LCJqdGkiOiI3MTMxOTdiMi0xZDRkLTQ0ODItOGRkMy0zZmZmMTJlNThhMzIiLCJlbWFpbCI6ImJvZ2F0b3ZnZWFAbWFpbC5ydSIsInJvbGUiOiJkZXZlbG9wZXIifQ.QLS_U5Q_O1v0n0Ob9_3DRy1dmZVdQ7-r5VZH0hkmrMc

### Get Users with filters
GET http://localhost:8080/public/v1/users?sort=asc&order=surname&offset=0&limit=20&role=developer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidXNlcnMiXSwiZXhwIjoxNzI3NTk1Mzk2LCJqdGkiOiJjMWNmZTRiOS1mN2MyLTQyM2MtYWJmYS02ZWQxYzA1YTE1YzUiLCJlbWFpbCI6ImJvZ2F0b3Zncm1uQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiJ9.crG6hDBiq3TntpE3W0HnqNJuCsrxbaicPFrv2-AuJUg


### Delete User By ID
DELETE http://localhost:8080/public/v1/users/bf56de11-b23d-4823-a148-732d8fc2bafc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTcyNzU1OTU1NiwianRpIjoiYmY1NmRlMTEtYjIzZC00ODIzLWExNDgtNzMyZDhmYzJiYWZjIiwiZW1haWwiOiJib2dhdG92Z0BtYWlsLnJ1Iiwicm9sZSI6ImRldmVsb3BlciJ9.QMY9f4uk34ay4gKEpBM9fTnQmGt1lOUDjl5kaX3RAqY

### Update User by ID

PATCH http://localhost:8080/public/v1/users/5127d211-cd89-45fb-afdf-86c025eea1eb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidXNlcnMiXSwiZXhwIjoxNzI3NTk2NDQ2LCJqdGkiOiI1MTI3ZDIxMS1jZDg5LTQ1ZmItYWZkZi04NmMwMjVlZWExZWIiLCJlbWFpbCI6ImJvZ2F0MXdlZWVAbWFpbC5ydSIsInJvbGUiOiJkZXZlbG9wZXIifQ.9gpjuGAjLP3n1cj6DPPg8GNa-bi25AUR0EAiNWrsGq4

{
  "name": "German",
  "surname": "Bogatov",
  "password": "qwerty12345"
}

### Update Private User by ID

PATCH http://localhost:8080/private/v1/users/ef904506-dc65-42c6-b44e-619ad805efd8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidXNlcnMiXSwiZXhwIjoxNzI3NTcyNzcwLCJqdGkiOiJjMWNmZTRiOS1mN2MyLTQyM2MtYWJmYS02ZWQxYzA1YTE1YzUiLCJlbWFpbCI6ImJvZ2F0b3Zncm1uQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiJ9.uKQKrKrQVgzYHk_MPJmS7u-K08IR49RppUuTWQ8ffSs

{

}