### Sign-up

POST http://localhost:8080/public/v1/auth/sign-up
Content-Type: application/json

{
  "name": "German",
  "surname": "Bogatov",
  "email": "bogatovgrmn@mail.ru",
  "password": "23Bogatov"
}

### Sign-in

POST http://localhost:8080/public/v1/auth/sign-in
Content-Type: application/json

{
  "email": "bogatovgrmn@mail.ru",
  "password": "23Bogatov"
}

### Refresh
GET http://localhost:8080/public/v1/auth/refresh/8a84f3af-c6aa-4364-ad4c-1ef53ed5e1e4
Content-Type: application/json


### Get User By ID
POST http://localhost:8080/public/v1/users/633d8ac3-c938-4c04-89f2-279e08add07c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1c2VycyIsImV4cCI6MTcyNzU0NTQyOSwianRpIjoiNjMzZDhhYzMtYzkzOC00YzA0LTg5ZjItMjc5ZTA4YWRkMDdjIiwiZW1haWwiOiJib2dhdG92Z3JtbkBtYWlsLnJ1Iiwicm9sZXMiOlsiZGV2ZWxvcGVyIl19.VefwQD3bBj2Ntzz6TqUDdAkda_PWHV6qq59Ylt70YdU

