server:
  port: 8081

spring:
  application:
    name: Project Task service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projecttaskdb}
    username: ${SPRING_DATASOURCE_USERNAME:amogus}
    password: ${SPRING_DATASOURCE_PASSWORD:amogus}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: project-task-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



logging:
  level:
    org:
      springframework:
        kafka: INFO
        jpa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info

application:
  title: Streamline Progress
  version: 1.0