version: "3.8"
networks:
  app-network:
    driver: bridge

services:
  #postgres
  database:
    networks:
      - app-network
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=amogus
      - POSTGRES_PASSWORD=amogus
      - POSTGRES_DB=postgres
    container_name: database
    ports:
      - "127.0.0.1:5432:5432"

  cache:
    networks:
      - app-network
    restart: always
    container_name: cache
    image: redislabs/redismod:latest
    ports:
      - "127.0.0.1:6380:6379"
    environment:
      - REDIS_DB=0

